-- if vim.fn.getenv("WEZTERM_EXECUTABLE") ~= vim.NIL or vim.fn.has("unix") == 1 then
--   return {
--     {
--       "folke/tokyonight.nvim",
--       opts = {
--         transparent = true,
--         styles = {
--           sidebars = "transparent",
--           floats = "transparent",
--         },
--       },
--     },
--   }
-- else
--   return {}
-- end
--
